---
- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: svc clusters
  vars:
    - user: username
    - hostname: svc clusters
    - username: superuser
    - password: 90EDbed8
  tasks:
    - name: Run CLI commands
      register: results
      ibm_svcinfo_command:
        command: "svcinfo lssystem"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        log_path: /tmp/test.debug
